### ISSUE TITLE
Markdown header IDs not parsed correctly

### ISSUE THREAD

**Issue by saswatamcode** [bwplotka/mdox#43]
Markdown headers like `## Expose UI on a sub-path` get parsed as id `expose-ui-on-subpath` which isn't correct as dash gets removed. Correct id should be `expose-ui-on-a-sub-path` as demonstrated [here](https://github.com/thanos-io/thanos/blob/main/docs/components/query.md#expose-ui-on-a-sub-path).

**Comment by bwplotka** [comment]
Nice!
